---
- name: Converge
  hosts: all

  pre_tasks:
    - name: create local archive directory
      file:
        state: directory
        mode: 'u=rwx,go=rx'
        dest: '{{ java_local_archive_dir }}'
      delegate_to: localhost
      when: java_use_local_archive

    - name: download JDK for offline install
      get_url:
        url: 'https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u262-b10/OpenJDK8U-jdk_x64_linux_hotspot_8u262b10.tar.gz'
        dest: '{{ java_local_archive_dir }}/OpenJDK8U-jdk_x64_linux_hotspot_8u262b10.tar.gz'
        force: no
        use_proxy: yes
        validate_certs: yes
        timeout: '{{ java_download_timeout_seconds }}'
        mode: 'u=rw,go=r'
      delegate_to: localhost
      when: java_use_local_archive

  roles:
    - role: ansible-role-java
      java_version: jdk8u262-b10
      java_use_local_archive: yes
      java_redis_filename: 'OpenJDK8U-jdk_x64_linux_hotspot_8u262b10.tar.gz'
      java_redis_sha256sum: '733755fd649fad6ae91fc083f7e5a5a0b56410fb6ac1815cff29f744b128b1b1'

  post_tasks:
    - name: verify java facts
      assert:
        that:
          - ansible_local.java.general.version is defined
          - ansible_local.java.general.home is defined

    - name: install find - required for tests (dnf)
      dnf:
        name: findutils
        state: present
      when: ansible_pkg_mgr == 'dnf'
