---
- name: Converge
  hosts: all

  pre_tasks:
    - name: create local archive directory
      file:
        state: directory
        mode: 'u=rwx,go=rx'
        dest: '{{ java_local_archive_dir }}'
      delegate_to: localhost

    - name: download JDK for offline install
      get_url:
        url: "https://api.adoptopenjdk.net/v2/binary/releases/openjdk11?openjdk_impl=hotspot&os=linux&arch=x64&release={{ 'jdk-11.0.6+10' | urlencode }}&type=jdk&heap_size=normal"  # noqa 204
        dest: '{{ java_local_archive_dir }}/OpenJDK11U-jdk_x64_linux_hotspot_11.0.6_10.tar.gz'
        force: no
        timeout: '{{ java_download_timeout_seconds }}'
        mode: 'u=rw,go=r'
      delegate_to: localhost

  roles:
    - role: ansible-role-java
      java_use_local_archive: yes
      java_version: 'jdk-11.0.6+10'
      java_redis_filename: 'OpenJDK11U-jdk_x64_linux_hotspot_11.0.6_10.tar.gz'
      java_redis_sha256sum: '330d19a2eaa07ed02757d7a785a77bab49f5ee710ea03b4ee2fa220ddd0feffc'

  post_tasks:
    - name: verify java facts
      assert:
        that:
          - ansible_local.java.general.version is defined
          - ansible_local.java.general.home is defined

    - name: install find - required for tests (dnf)
      dnf:
        name: findutils
        state: present
      when: ansible_pkg_mgr == 'dnf'
