---
language: python
python: '2.7'

env:
  global:
    - MOLECULEW_USE_SYSTEM=true

matrix:
  include:
    - env:
        - MOLECULE_SCENARIO=ubuntu-min-java-min-online
        - MOLECULEW_ANSIBLE=2.4.6
    - env:
        - MOLECULE_SCENARIO=ubuntu-min-java-max-online
        - MOLECULEW_ANSIBLE=2.4.6
    - env:
        - MOLECULE_SCENARIO=ubuntu-max-java-min-offline
        - MOLECULEW_ANSIBLE=2.7.0
    - env:
        - MOLECULE_SCENARIO=ubuntu-max-java-max-offline
        - MOLECULEW_ANSIBLE=2.7.0
    - env:
        - MOLECULE_SCENARIO=debian-min-java-min-online
        - MOLECULEW_ANSIBLE=2.4.6
    - env:
        - MOLECULE_SCENARIO=debian-min-java-max-online
        - MOLECULEW_ANSIBLE=2.4.6
    - env:
        - MOLECULE_SCENARIO=debian-max-java-min-offline
        - MOLECULEW_ANSIBLE=2.7.0
    - env:
        - MOLECULE_SCENARIO=debian-max-java-max-offline
        - MOLECULEW_ANSIBLE=2.7.0
    - env:
        - MOLECULE_SCENARIO=centos-min-java-min-online
        - MOLECULEW_ANSIBLE=2.4.6
    - env:
        - MOLECULE_SCENARIO=centos-min-java-max-online
        - MOLECULEW_ANSIBLE=2.4.6
    - env:
        - MOLECULE_SCENARIO=centos-max-java-min-offline
        - MOLECULEW_ANSIBLE=2.7.0
    - env:
        - MOLECULE_SCENARIO=centos-max-java-max-offline
        - MOLECULEW_ANSIBLE=2.7.0
    - env:
        - MOLECULE_SCENARIO=fedora-java-min-online
        - MOLECULEW_ANSIBLE=2.4.6
    - env:
        - MOLECULE_SCENARIO=opensuse-java-min-online
        - MOLECULEW_ANSIBLE=2.4.6
    - env:
        - MOLECULE_SCENARIO=fedora-java-min-online
        - MOLECULEW_ANSIBLE=2.7.0
    - env:
        - MOLECULE_SCENARIO=opensuse-java-min-online
        - MOLECULEW_ANSIBLE=2.7.0

# Require the standard build environment
sudo: required

# Require Ubuntu 14.04
dist: trusty

# Require Docker
services:
  - docker

install:
  # Install dependencies
  - ./moleculew wrapper-install

  # Display versions
  - ./moleculew wrapper-versions

script:
  - ./moleculew test --scenario-name=$MOLECULE_SCENARIO

branches:
  only:
    - master
    - develop
    - /^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)([\.\-].*)?$/

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
