---
language: python
python: '2.7'

matrix:
  include:
    - env:
        # Molecule 1 tests for Ansible 2.0, Fedora and OpenSUSE.
        - MOLECULE_SCENARIO=
        - ANSIBLE_VERSION=2.0.2
        # Limit version as workaround for: https://github.com/ansible/ansible/issues/35612
        - DOCKER_LIB='docker<3.0'
        - MOLECULE_VERSION=1.24
    - env:
        - MOLECULE_SCENARIO=ubuntu-trusty-online
        - ANSIBLE_VERSION=2.2.0
        - DOCKER_LIB=docker-py
        - MOLECULE_VERSION=2.11
    - env:
        - MOLECULE_SCENARIO=ubuntu-trusty-java9
        - ANSIBLE_VERSION=2.2.0
        - DOCKER_LIB=docker-py
        - MOLECULE_VERSION=2.11
    - env:
        - MOLECULE_SCENARIO=ubuntu-xenial-offline
        - ANSIBLE_VERSION=2.4.3
        # Limit version as workaround for: https://github.com/ansible/ansible/issues/35612
        - DOCKER_LIB='docker<3.0'
        - MOLECULE_VERSION=2.11
    - env:
        - MOLECULE_SCENARIO=ubuntu-xenial-java9
        - ANSIBLE_VERSION=2.4.3
        # Limit version as workaround for: https://github.com/ansible/ansible/issues/35612
        - DOCKER_LIB='docker<3.0'
        - MOLECULE_VERSION=2.11
    - env:
        - MOLECULE_SCENARIO=debian-wheezy-online
        - ANSIBLE_VERSION=2.2.0
        - DOCKER_LIB=docker-py
        - MOLECULE_VERSION=2.11
    - env:
        - MOLECULE_SCENARIO=debian-wheezy-java9
        - ANSIBLE_VERSION=2.2.0
        - DOCKER_LIB=docker-py
        - MOLECULE_VERSION=2.11
    - env:
        - MOLECULE_SCENARIO=debian-jessie-offline
        - ANSIBLE_VERSION=2.4.3
        # Limit version as workaround for: https://github.com/ansible/ansible/issues/35612
        - DOCKER_LIB='docker<3.0'
        - MOLECULE_VERSION=2.11
    - env:
        - MOLECULE_SCENARIO=debian-jessie-java9
        - ANSIBLE_VERSION=2.4.3
        # Limit version as workaround for: https://github.com/ansible/ansible/issues/35612
        - DOCKER_LIB='docker<3.0'
        - MOLECULE_VERSION=2.11
    - env:
        - MOLECULE_SCENARIO=centos-6-online
        - ANSIBLE_VERSION=2.2.0
        - DOCKER_LIB=docker-py
        - MOLECULE_VERSION=2.11
    - env:
        - MOLECULE_SCENARIO=centos-6-java9
        - ANSIBLE_VERSION=2.2.0
        - DOCKER_LIB=docker-py
        - MOLECULE_VERSION=2.11
    - env:
        - MOLECULE_SCENARIO=centos-7-offline
        - ANSIBLE_VERSION=2.4.3
        # Limit version as workaround for: https://github.com/ansible/ansible/issues/35612
        - DOCKER_LIB='docker<3.0'
        - MOLECULE_VERSION=2.11
    - env:
        - MOLECULE_SCENARIO=centos-7-java9
        - ANSIBLE_VERSION=2.4.3
        # Limit version as workaround for: https://github.com/ansible/ansible/issues/35612
        - DOCKER_LIB='docker<3.0'
        - MOLECULE_VERSION=2.11
    # Fedora and OpenSUSE are not currently working with Molecule 2.0.
    # - env:
    #     - MOLECULE_SCENARIO=fedora-25-online
    #     - ANSIBLE_VERSION=2.4.3
    #     # Limit version as workaround for: https://github.com/ansible/ansible/issues/35612
    #     - DOCKER_LIB='docker<3.0'
    #     - MOLECULE_VERSION=2.11
    # - env:
    #     - MOLECULE_SCENARIO=opensuse-leap-online
    #     - ANSIBLE_VERSION=2.4.3
    #     # Limit version as workaround for: https://github.com/ansible/ansible/issues/35612
    #     - DOCKER_LIB='docker<3.0'
    #     - MOLECULE_VERSION=2.11

# Require the standard build environment
sudo: required

# Require Ubuntu 14.04
dist: trusty

# Require Docker
services:
  - docker

# Cache Ansible and Molecule to speed things up
cache:
  - pip

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -o Dpkg::Options::='--force-confold' --force-yes -y docker-ce

install:
  # Install Ansible
  - pip install "ansible~=$ANSIBLE_VERSION"

  # Install Python API for Docker (required by Molecule Docker driver)
  - pip install "$DOCKER_LIB"

  # Install Molecule
  - pip install "molecule==$MOLECULE_VERSION"

  # Check Ansible version
  - ansible --version

  # Check Molecule version
  - molecule --version

  # Build the Docker images
  - .travis/docker-build.sh

script:
  - .travis/build.sh

branches:
  only:
    - master
    - /^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)([\.\-].*)?$/

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
