---
language: python
python: '2.7'

env:
  global:
    - MOLECULEW_USE_SYSTEM=true

matrix:
  include:
    - env:
        - MOLECULE_SCENARIO=ubuntu-min-java-min-online
        - MOLECULEW_ANSIBLE=2.7.15
    - env:
        - MOLECULE_SCENARIO=ubuntu-min-java-max-lts-online
        - MOLECULEW_ANSIBLE=2.7.15
    - env:
        - MOLECULE_SCENARIO=ubuntu-max-java-min-offline
        - MOLECULEW_ANSIBLE=2.9.1
    - env:
        - MOLECULE_SCENARIO=ubuntu-max-java-max-lts-offline
        - MOLECULEW_ANSIBLE=2.9.1
    - env:
        - MOLECULE_SCENARIO=debian-min-java-min-online
        - MOLECULEW_ANSIBLE=2.7.15
    - env:
        - MOLECULE_SCENARIO=debian-min-java-max-lts-online
        - MOLECULEW_ANSIBLE=2.7.15
    - env:
        - MOLECULE_SCENARIO=debian-max-java-min-offline
        - MOLECULEW_ANSIBLE=2.9.1
    - env:
        - MOLECULE_SCENARIO=debian-max-java-max-lts-offline
        - MOLECULEW_ANSIBLE=2.9.1
    - env:
        - MOLECULE_SCENARIO=centos-min-java-min-online
        - MOLECULEW_ANSIBLE=2.7.15
    - env:
        - MOLECULE_SCENARIO=centos-min-java-max-lts-online
        - MOLECULEW_ANSIBLE=2.7.15
    - env:
        - MOLECULE_SCENARIO=centos-max-java-min-offline
        - MOLECULEW_ANSIBLE=2.9.1
    - env:
        - MOLECULE_SCENARIO=centos-max-java-max-lts-offline
        - MOLECULEW_ANSIBLE=2.9.1
    - env:
        - MOLECULE_SCENARIO=fedora-java-min-online
        - MOLECULEW_ANSIBLE=2.7.15
    - env:
        - MOLECULE_SCENARIO=opensuse-java-min-online
        - MOLECULEW_ANSIBLE=2.7.15
    - env:
        - MOLECULE_SCENARIO=fedora-java-min-online
        - MOLECULEW_ANSIBLE=2.9.1
    - env:
        - MOLECULE_SCENARIO=opensuse-java-min-online
        - MOLECULEW_ANSIBLE=2.9.1
    - env:
        - MOLECULE_SCENARIO=ubuntu-min-java-max-non-lts-online
        - MOLECULEW_ANSIBLE=2.7.15
    - env:
        - MOLECULE_SCENARIO=ubuntu-max-java-max-non-lts-offline
        - MOLECULEW_ANSIBLE=2.9.1

# Require the standard build environment
sudo: required

# Require Ubuntu 16.04
dist: xenial

# Require Docker
services:
  - docker

install:
  # Install dependencies
  - ./moleculew wrapper-install

  # Display versions
  - ./moleculew wrapper-versions

script:
  - ./moleculew test --scenario-name=$MOLECULE_SCENARIO

cache:
  directories:
    - $HOME/.moleculew

branches:
  only:
    - master
    - develop
    - /^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)([\.\-].*)?$/

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
