---
- name: query version info
  uri:
    url: '{{ java_api_request }}'
    return_content: yes
  register: java_api_response

- name: set full version var from API
  set_fact:
    java_full_version: '{{ (java_api_response.json[0] | default(java_api_response.json)).release_name }}'
  when: java_release == 'latest'

- name: set JDK URL var from API
  set_fact:
    java_redis_url: '{{ (java_api_response.json[0] | default(java_api_response.json)).binaries[0].binary_link }}'
  when:
    - java_redis_mirror in (None, '', omit)
    - java_redis_filename in (None, '', omit) or not remote_JDK_file.stat.exists

- name: set checksum URL var from API
  set_fact:
    java_redis_sha256sum_url: '{{ (java_api_response.json[0] | default(java_api_response.json)).binaries[0].checksum_link }}'

- name: set JDK filename var from API
  set_fact:
    java_redis_filename: '{{ (java_api_response.json[0] | default(java_api_response.json)).binaries[0].binary_name }}'
  when: java_redis_filename in (None, '', omit)
