---
- name: Converge
  hosts: all

  pre_tasks:
    - name: create local archive directory
      file:
        state: directory
        mode: 'u=rwx,go=rx'
        dest: '{{ java_local_archive_dir }}'
      delegate_to: localhost

    - name: download JDK for offline install
      get_url:
        url: "https://api.adoptopenjdk.net/v2/binary/releases/openjdk12?openjdk_impl=hotspot&os=linux&arch=x64&release={{ 'jdk-12+33' | urlencode }}&type=jdk&heap_size=normal"  # noqa 204
        dest: '{{ java_local_archive_dir }}/OpenJDK12U-jdk_x64_linux_hotspot_12_33.tar.gz'
        force: no
        timeout: '{{ java_jdk_download_timeout_seconds }}'
        mode: 'u=rw,go=r'
      delegate_to: localhost

  roles:
    - role: ansible-role-java
      java_use_local_archive: yes
      java_version: 'jdk-12+33'
      java_redis_filename: 'OpenJDK12U-jdk_x64_linux_hotspot_12_33.tar.gz'
      java_redis_sha256sum: '4739064dc439a05487744cce0ba951cb544ed5e796f6c699646e16c09da5dd6a'

  post_tasks:
    - name: verify java facts
      assert:
        that:
          - ansible_local.java.general.version is defined
          - ansible_local.java.general.home is defined

    - name: install find - required for tests (dnf)
      dnf:
        name: findutils
        state: present
      when: ansible_pkg_mgr == 'dnf'
